#!/usr/bin/env ruby

require 'bicho'

server = Bicho::Client.new('https://bugzilla.suse.com')
ARGV.each do |id| 
  server.get_bugs(id).each do |bug|  
    puts "#{id}:short_desc:\"#{bug.summary}\""
    puts "#{id}:priority:\"#{bug.priority}\""
    puts "#{id}:severity:\"#{bug.severity}\""
    puts "#{id}:deltats:\"#{bug.delta_ts}\""
    puts "#{id}:bug_status:\"#{bug.status}\""
    puts "#{id}:whiteboard:\"#{bug.whiteboard}\""
  end  
end


