#!/usr/bin/env ruby

require 'jira-ruby'
require 'parseconfig'
require 'pp'

config = ParseConfig.new('/home/uwe/.eb-login')

options = {
  :username     => config['username'],
  :password     => config['password'],
  :site         => 'https://ticket.asw.zone/',
  :context_path => '',
  :auth_type    => :basic
}

client = JIRA::Client.new(options)

ARGV.each do |id| 

  # Query ticket and display info
  t = client.Issue.find(id)
  puts "#{id}:short_desc:\"#{t.summary}\""
  puts "#{id}:priority:\"#{t.priority.name}\""
  puts "#{id}:status:\"#{t.status.name}\""
  puts "#{id}:created:\"#{t.created[0..15]}\""
  puts "#{id}:updated:\"#{t.updated[0..15]}\""
  puts "#{id}:reporter:\"#{t.updated[0..15]}\""
  s = ""
  s = t.assignee.emailAddress if ! t.assignee.nil? 
  puts "#{id}:assignee:\"#{s}\""
end
