#!/bin/bash

CONFIG=makedist.config

if [ ! -f $CONFIG ]; then
    echo Configuration missing: $CONFIG
    echo Please set the following variables in $CONFIG
    echo in you current directory:
    echo
    echo 'VERSION=x.y.z   # override version from src/version.h'
    echo 'Tag=vx.y.z   # If given, checkout this version instead of HEAD'
    echo 'BRANCH="develop" #or e.g. "maintained-release"'
    exit
else    
    . $CONFIG
fi    

# Init
OLDDIR=$(pwd)
SRCDIR=$OLDDIR/vym
TMPDIR=$OLDDIR/tmp

if [ -z "$TAG" ]; then
    TAG="not provided"
fi

if [ -z "$VERSION" ]; then
    VERSION="not provided"
fi

echo "Getting sources for: vym"  
echo "             Branch: $BRANCH"
echo "            Version: $VERSION"
echo "                Tag: $TAG"
echo "  Working directory: $OLDDIR"
echo 


if [ -d $TMPDIR ]; then
#    read -n 1 -p "$TMPDIR exists: Remove it first? [y]" INPUT
#    if [ ! "$INPUT" = "n" ]; then
        echo Removing $TMPDIR...
	rm -rf $TMPDIR
#    fi	
fi
#echo
mkdir $TMPDIR

DO_CHECKOUT=1
#read -n 1 -p "Pull from git repository ? [y]" INPUT
#if [ "$INPUT" = "n" ]; then
#    DO_CHECKOUT=0
#fi	
#echo

#read -n 1 -p "Create Documentation? [y]" INPUT
#DO_DOCS=1
#if [ "$INPUT" = "n" ]; then
#    DO_DOCS=0
#fi	
#echo

DO_TARBALL=1
#read -n 1 -p "Create Tarball? [y]" INPUT
#if [ "$INPUT" = "n" ]; then
#    DO_TARBALL=0
#fi	
#echo

DO_REMOVE=1
#echo -n "Remove unpacked sources after creating tarball? [y]"
#echo "(do this before  \"osc addremove\")"
#read -n 1 INPUT
#if [ "$INPUT" = "n" ]; then
#    DO_REMOVE=0
#fi	
#echo

# get data from repository
if [ $DO_CHECKOUT = 1 ]; then
    cd $OLDDIR
    echo Removing $SRCDIR...
    rm -rf $SRCDIR
    if [ "$TAG" != "not provided" ]; then
        echo "Cloning '$TAG' from $REPOSITORY"
        git clone --quiet --depth 1 -b $TAG $REPOSITORY vym
    else
        echo Cloning head of $BRANCH from $REPOSITORY
        git clone --quiet --depth 1 -b $BRANCH $REPOSITORY vym
    fi
fi	

srcVersion=$(grep __VYM_VERSION $SRCDIR/src/version.h |  sed -e 's/^.*\"\(.*\)\"$/\1/g')
vymDirName=vym-$srcVersion
if [ "$VERSION" != "not provided" ]; then
    echo "Warning: Overriding version from sources '$srcVersion' with '$VERSION' from config"
    vymDirName=vym-$VERSION
else
    echo "Using version '$srcVersion' from sources"
fi

# create documentation
#if [ $DO_DOCS = 1 ] ; then
#    cp -ra $SRCDIR/tex $TMPDIR
#    cp -ra $SRCDIR/icons $TMPDIR
#    cp -ra $SRCDIR/flags $TMPDIR
#    cd $TMPDIR/tex
#    for i in {1..3} ; do
#	pdflatex vym.tex
#	pdflatex vym_es.tex
#	pdflatex vym_fr.tex
#	sleep 1
#    done	
#    cd $OLDDIR
#fi

cd $OLDDIR

# create tarball
if [ $DO_TARBALL = 1 ]; then
    tarballName=$vymDirName.tar.bz2
    echo "Creating $tarballName..."
    if [ -d $tarballName ] ;  then
	rm -rf $tarballName
    fi
    cp -ra $SRCDIR $vymDirName

    rm -rf vymDirName/.git

    tar cjf $tarballName $vymDirName

    if [ $DO_REMOVE = 1 ]; then
        echo Removing $vymDirName...
	rm -rf $vymDirName
    fi
fi
