#!/bin/bash

VYMDIR=~/vym/code
MAP=$VYMDIR/../maps/screencasts/ao-report.vym

$VYMDIR/vym -l -n test \
  -geometry 1280x720+0+0 \
  $MAP &

xvidcap --audio no --cap_geometry 1280x720+0+0 --continue --file xxout.mpeg
